config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  match "/" => "pages#home", via: [:gets, :post]


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies, :only => [:show]

  resources :divisions, :only => [:index, :new, :create, :show, :destroy, :edit] do

  	member  do 
		  get "generate"
      post "preview"
      get "preview"
      get "completed_job"
  	end  
  end
  get '/robots' => 'pages#robots'
  get '/:id' => 'companies#show'


end

app/models/division.rb
class Division < ApplicationRecord
	
	belongs_to :company

	has_and_belongs_to_many :card_fields, :join_table => 'card_fields_divisions'
	has_and_belongs_to_many :email_sig_fields, :join_table => 'divisions_email_sig_fields'
	has_many :card_images


	attr_accessor :email_receiver

	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	extend FriendlyId
	friendly_id :name, use: :slugged

  	extend Dragonfly::Model
  	extend Dragonfly::Model::Validations



	dragonfly_accessor :image
	dragonfly_accessor :image_back
	dragonfly_accessor :image_cut
	dragonfly_accessor :image_preview_front
	dragonfly_accessor :image_preview_back
	dragonfly_accessor :email_sig_template
	dragonfly_accessor :default_email_sig_image
	dragonfly_accessor :crew_card_image_front
	dragonfly_accessor :crew_card_image_back
	dragonfly_accessor :crew_card_image_preview_front
	dragonfly_accessor :crew_card_image_preview_back
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController 

  before_action :set_division, only: [:show, :generate, :preview, :completed_job, :create_email_sig] 
  before_action :set_company, only: [:generate, :show, :preview, :completed_job]
  before_action :set_images, only: [:show, :preview, :generate]

	def index 
    
    @company = Company.where(slug: params[:company]).first
    @divisions = @company.divisions
    session[:function] = params[:function] if !params[:function].nil?

    if @company.divisions.count == 1
      division = @company.divisions.first
      redirect_to generate_division_path(division)
    
    #I'M SORRY FOR THIS UGLY HACK :/
    elsif @company.slug == "airschool43" and params[:function] != "crew_card"

      redirect_to generate_division_path(@divisions.first)
    end
  
  end

	def show
    
     if session[:function] == 'business_card' or session[:function] == 'crew_card'

      @card_fields = CardField.where(function: session[:function]).joins(:divisions).where("division_id = ? ",@division.id)

      puts "CARD FIELDS params!!!!!!!!!!!!!#{params["40"]}"
        #THIS HAS TO BE CLEANED UP
        if @card_fields.where(name: "Associate Name").exists?
          card_holder_name = params[:"#{@card_fields.where(name: "Associate Name").last.id}"]
        elsif @card_fields.where(name: "Name Surname").exists?
          card_holder_name = params[:"#{@card_fields.where(name: "Name Surname").last.id}"]
        end
        if @card_fields.where(name: "email").exists?
          card_holder_email = params[:"#{@card_fields.where(name: "email").last.id}"]
        end
        purchase_order_number =  params[:"Purchase Order"]
        #UP TO HERE

        #CONCAT name and name line 2 if name line 2 is not empty
        if @card_fields.where(name: "Name line 2 if needed").exists?
            card_holder_name2 = params[:"#{@card_fields.where(name: "Name line 2 if needed").last.id}"]
            unless card_holder_name2 == ""
              card_holder_name2 = " " + card_holder_name2  
            end
            card_holder_name =  card_holder_name + card_holder_name2
        end
        #END CONCAT


      #create specific pdf for adendorf because its fields are right aligned
          if @company.name.downcase == 'adendorff'
           render :pdf => "filename.pdf",
            :template => 'divisions/create_pdf.html.erb',#, :show_as_html => true
                  :page_height => "#{@card_front.height / 300.0 *  25.4}",
                  :page_width => "#{@card_front.width / 300.0 * 25.4}",
                    margin:  { top: 0, bottom: 3, left: 1, right: 0 },
                      :align => 'right',
                        :save_to_file => Rails.root.join('tmp', "filename.pdf"),                                  
                            :show_as_html => false, :dpi => '300', :save_only => true
          else
            render :pdf => "filename.pdf",
                   :template => 'divisions/create_pdf.html.erb',#, :show_as_html => true
                   :page_height => "#{@card_front.height / 300.0 *  25.4}",
                   :page_width => "#{@card_front.width / 300.0 * 25.4}",
                   margin:  { top: 10, bottom: 3, left: 5, right: 0 },
                   :align => 'right',
                   :save_to_file => Rails.root.join('tmp', "filename.pdf"),
                   :show_as_html => false, :dpi => '300', :save_only => true
          end


        @file2 = Tempfile.new('temp_route_pdf', "#{Rails.root}/tmp/")
        #CUT OFF LAST BLANK PAGE
        if @division.image_cut.present?
          final_page = 3
        else
          final_page = 2
        end
         `pdftk "#{Rails.root}/tmp/filename.pdf" cat 1-"#{final_page}" output "#{@file2.path}"`
        #CUT OFF LAST BLANK PAGE FINISHED    

        if session[:function] == 'business_card' and @company.slug == 'coca-cola'
          PdfMailer.cocacola(@file2.path,@division, card_holder_name, card_holder_email, purchase_order_number).deliver 
        elsif @company.slug == 'airschool43'
          #raise
          PdfMailer.airschool43(@file2.path,@division, card_holder_name, card_holder_email, purchase_order_number).deliver 
        elsif @company.slug == 'adendorff'
          adendorff_card_holder_email = params["40"]
          PdfMailer.adendorff(@file2.path,@division, card_holder_name, adendorff_card_holder_email, purchase_order_number).deliver
        else
          
        end
        redirect_to completed_job_division_path
    end
    #END OF CARD FUNCTION
    if session[:function] == 'email_sig'
    end
  end



  def completed_job
    if session[:function] == "business_card" or session[:function] == "crew_card"
      render :template => 'divisions/completed_card.html.erb'
    end
  end

	def new
		@division = Division.new
	end

  def generate

    if session[:function] == 'business_card' or session[:function] == 'crew_card'

      @card_fields = CardField.where(function: session[:function]).joins(:divisions).where("division_id = ? ",@division.id)

      unless params[:back].present?
          session.delete(:field_inputs)
      end
      render :template => 'divisions/generate_card.html.erb'
    end

    if session[:function] == "email_sig"
      @email_sig_fields = EmailSigField.all
      unless params[:back].present?
          session.delete(:field_inputs)
      end

      #REPLACE "IMAGE" STRING WITH DEFAULT IMAGE:
      create_email_sig
      @generated_email_sig = @generated_email_sig.gsub("IMAGE", "/assets/#{@division.default_email_sig_image.name}")
      File.write(@generated_email_sig_file.path, "#{@generated_email_sig}")
      #COMPLETE: DEFAULT IMAGE PLACED

      render :template => 'divisions/generate_email_sig.html.erb'
    end

  end

  def preview
    if session[:function] == 'business_card' or session[:function] == 'crew_card'

      @card_fields = CardField.where(function: session[:function]).joins(:divisions).where("division_id = ? ",@division.id)

      unless params[:returning]
        session[:field_inputs] = params[:field_inputs].each do |field| field end
        @card_fields = CardField.where(function: session[:function]).joins(:divisions).where("division_id = ? ",@division.id)
      end
      #render :template => 'divisions/preview_card.html.erb'
   
      if @division.card_images.where(function: session[:function]).where(user_upload: true).exists?
        
        session[:image_path] = []
        @division.card_images.where(function: session[:function]).where(user_upload: true).each do |image|
          session["image_#{image.id}"] = params["image_#{image.id}"].original_filename
          directory = "#{Rails.root}/public/assets"
          session[:image_path][image.id] = File.join(directory, session["image_#{image.id}"])
          File.open(session[:image_path][image.id], "wb") { |f| f.write(params["image_#{image.id}"].read) }
        end

        @division.card_images.where(function: session[:function]).where(user_upload: true).each do |image|
          if @division.card_images.where(function: session[:function]).where(user_upload: true).present?

            session[:x_res] = FastImage.size(session[:image_path][image.id])[0].to_f
            session[:y_res] = FastImage.size(session[:image_path][image.id])[1].to_f
          end
        end
        
        session[:x_axis] = params[:x_axis]
        session[:y_axis] = params[:y_axis]
        session[:scale] = params[:scale]
        session[:width] = params[:width]
        session[:height] = params[:height] 
      end
      render :template => 'divisions/preview_card.html.erb'
    end    

    if session[:function] == 'email_sig'

      unless params[:returning]

        session[:field_inputs] = params[:field_inputs].each do |field| field end
        @email_sig_fields = EmailSigField.all
      end
      create_email_sig


      puts "GENERATE PARAMS::::: #{params}"
      puts "Session fields: #{session[:field_inputs]}"
      @params = params

      File.write(@generated_email_sig_file.path, "#{@generated_email_sig}")

      puts "------------------------#{@generated_email_sig}"
      render :template => 'divisions/preview_email_sig.html.erb'
    end
  end


  private

  def division_params
    params.require(:division).permit(:name, :image, :image_back, :image_cut, :image_preview_front, :image_preview_back, :slug, :email_choice, :associate_name)
  end

  def set_division
    @division = Division.find_by_slug(params[:id])
  end

  def set_company
    @company = @division.company   
  end

  def create_email_sig

    @generated_email_sig_file = Tempfile.new('temp_route_sig', "#{Rails.root}/tmp/")
    @generated_email_sig = File.read(@division.email_sig_template.path)
    #REPLACE FIELDS IN TEMPLATE WITH INPUT + PREFIX
    if session[:field_inputs].present?
      session[:field_inputs].each do |field| 
        if field[1].empty?
          @generated_email_sig = @generated_email_sig.gsub(field[0],"")
        else
          @generated_email_sig = @generated_email_sig.gsub(field[0],@division.email_sig_fields.where(replace_field: field[0]).first.prefix + " " + field[1])
        end
      end
    end
  end

  #BELOW ENABLES THE RE-USE OF BCG FOR CALLCARDS ETC.
  def set_images
    if session[:function] == 'business_card'
      @card_front = @division.image
      @card_back  = @division.image_back 
      @card_front_preview = @division.image_preview_front
      @card_back_preview  = @division.image_preview_back
    elsif session[:function] == 'crew_card'
      @card_front = @division.crew_card_image_front
      @card_back  = @division.crew_card_image_back
      @card_front_preview = @division.crew_card_image_preview_front
      @card_back_preview  = @division.crew_card_image_preview_back
    end


  end

end

app/views/divisions/_completed_card_header.html.erb
	


 <%if @company.slug == 'coca-cola' and session[:function] == 'business_card'%>
	<%= image_tag(@company.company_logo.remote_url) %>
    <h1>Thank you! <br></h1><h2>We’re busy sharing the happiness! Proof of your business card has been sent directly to you, the Head of Department and the Printers!</h2>
<%elsif session[:function] == 'business_card' %>
	<%= image_tag(@company.company_logo.remote_url) %>
    <h1>Thank you! <br></h1><h2>Proof of your business card has been sent directly to you, the Head of Department and the Printers!</h2>
<%elsif session[:function] == 'crew_card' %>
	<%= image_tag(@company.company_logo.remote_url) %>
    <h1>Thank you! <br></h1><h2>Proof of your crew card has been sent to the Head of Department and the Printers!</h2>
<% end %>

app/views/divisions/_generate_card_header.html.erb
<%if @company.slug == 'coca-cola' and session[:function] == 'business_card'%>
	<%= image_tag(@company.company_logo.remote_url) %>
    <h1>Business Card for Department: <br> <strong> <%=@division.name%>  </strong></h1><h2>You’re one step closer! Be sure to fill in all your details carefully.<br>Once you’re happy that everything is correct, click the “Generate” button and wait for the next page to load. </h2>
<%elsif session[:function] == 'business_card' %>
		<%= image_tag(@company.company_logo.remote_url) %>
		<h1> Business Card Generator  </h1><h2>You’re one step closer! Be sure to fill in all your details carefully.<br>Once you’re happy that everything is correct, click the “Generate” button and wait for the next page to load. </h2>
<%elsif session[:function] == 'crew_card' %>
		<%= image_tag(@company.company_logo.remote_url) %>
		<h1>Crew Card Generator </h1><h2>You’re one step closer! Be sure to fill in all your details carefully.<br>Once you’re happy that everything is correct, click the “Generate” button and wait for the next page to load. </h2>
<%else %>
  <%= image_tag(@company.company_logo.remote_url) %>
  <h1>Business Card for Department: <br> <strong> <%=@division.name%>  </strong></h1><h2>You’re one step closer! Be sure to fill in all your details carefully.<br>Once you’re happy that everything is correct, click the “Generate” button and wait for the next page to load. </h2>
<% end %>

app/views/divisions/generate_card.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>

<div class="se-pre-con-<%=@company.slug%>"></div>
<div class="container details <%=@company.slug%>">
    <div class="row details-row1">
        <div class="col-xs-12">
          <%= render 'generate_card_header' %>    
        </div>       
    </div>
    
	<div class="row" style= "padding: 40px 214px 0;">
		<div class="col-xs-6 form-input">
			<%= form_tag(preview_division_path, multipart: true) do %>
				<% @card_fields.order(:order).each do |field| %>
					<% next unless field.default == "" or field.default == nil%>
		 			<div class="form-group">
		    			<%= label_tag "#{field.name}:" %>
<!-- TODO: REFACTOR OUT THE HACK PREPOPULATE HACK FOR COCACOLA DIVISIONS-->
  			    	<%= text_field_tag "field_inputs[field_#{field.id}]", (session[:field_inputs].present? and session[:field_inputs]["field_#{field.id}"].present?) ? session[:field_inputs]["field_#{field.id}"] : field.pre_populate.present? ? @division.name : nil , {class: 'form-control'} %>
            
            		</div>    
    			<%end%><br>
				<% @division.card_images.where(function: session[:function]).where(user_upload: true).each do |image| %>
					<div class="form-group">
  						<div class="photo-uploader">
        					<div class="photo-input">
	            				<div class="photo-container" style="width:60%; display:none;" data-guillotine-width="<%=image.x_size%>" data-guillotine-height="<%=image.y_size%>">
								</div>
	          					<div id="guillotine-controls" style="display:none;">
						            <!-- <a href="javascript:void(0)" id="rotate_left" title="Rotate left"><i class="ion-reply"></i></a> -->
						            <a href="javascript:void(0)" id="zoom_out" title="Zoom out"><i class="ion-minus-circled"></i></a>
						            <a href="javascript:void(0)" id="fit" title="Fit image"><i class="ion-arrow-shrink"></i></a>
						            <a href="javascript:void(0)" id="zoom_in" title="Zoom in"><i class="ion-plus-circled"></i></a>
						            <!-- <a href="javascript:void(0)" id="rotate_right" title="Rotate right"><i class="ion-forward"></i></a> -->
	          					</div>
					            <%= hidden_field_tag :scale %>
					            <%= hidden_field_tag :angle %>
					            <%= hidden_field_tag :x_axis %>
					            <%= hidden_field_tag :y_axis %>
					            <%= hidden_field_tag :width %>
					            <%= hidden_field_tag :height %>		
	    						<%= file_field_tag "image_#{image.id}", id: "upload", required: true %>
          					</div>
    					</div>
        			</div>
	      		<%end%><!--END OF EACH STATEMENT -->						
				<div>
					<% if @company.slug == "coca-cola" %>
					<%= link_to 'Back to Functions', divisions_path(company: @company, function: params[:function]), class: "btn-default #{@company.slug}-border #{@company.slug}" %>
					<% elsif @company.slug == "airschool43" %>
					<%= link_to 'Back Home', company_path(id: @company.slug), class: "btn-default #{@company.slug}-border #{@company.slug}" %>
					<% end %>
					<input type="submit" name="commit" value="Generate" class="btn-default <%=@company.slug%>-bg" >
				</div>
			<%end%>			
		</div>
		<div class="col-xs-6 cards">
		    <div class="bgimg"><%= image_tag(@card_front_preview.remote_url) %></div>
		    <div class="bgimg2"><%= image_tag(@card_back_preview.remote_url) %></div>
    	</div>
	</div>
</div>

<style type="text/css">
	.ion-minus-circled {
  		font-size: 25px;

	}
	.ion-arrow-shrink  {
  		font-size: 25px;

	}
	.ion-plus-circled {
  		font-size: 25px;

	}
</style>

app/views/divisions/generate_email_sig.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>

  <!-- <div class="se-pre-con-<%=@company.slug%>"></div> -->
  <div class="container details <%=@company.slug%>">
    <div class="row details-row1">
        <div class="col-xs-12">
        	<%= render 'generate_email_sig_header'%>     
        </div>       
    </div>
	<div class="row" style= "padding: 40px 214px 0;">

		<div class="col-xs-12 cards">
			<%# raise %>
			<%= image_tag(@division.default_email_sig_image.remote_url) %>
			<%#= render file:  @generated_email_sig_file.path, layout: false, content_type: 'html' %>
    	</div>


		<div class="col-xs-6 form-input" style="width: 100%">
			<%= form_tag(preview_division_path, multipart: true) do %>
			 	<div class="form-group">
			 		<% EmailSigField.joins(:divisions).where("division_id = ? ",@division.id).order(:order).each do |field| %>
				 		<div class="form-group">
				 				<%# raise %>
				    			<%= label_tag "#{field.replace_field}:" %>
				    			<%= text_field_tag "field_inputs[#{field.replace_field}]", (session[:field_inputs].present? and session[:field_inputs]["#{field.replace_field}"].present?) ? session[:field_inputs]["#{field.replace_field}"] : nil , {class: 'form-control'} %>
				 		</div>
					<%end%>	<br> 	
				<!-- TODO: UPLOAD PICTURE ONLY IF TEMPLATE CONTAINS STRING "USER_IMAGE" -->
  				<!-- <%= file_field_tag :picture %> -->
				<!-- TODO: UPLOAD PICTURE ONLY IF TEMPLATE CONTAINS STRING "USER_IMAGE" -->
				</div>
				<div>
					<%= link_to 'Back Home', company_path(@division.company, function: params[:function]), class: "btn-default #{@company.slug}-border #{@company.slug}" %>
					<input type="submit" name="commit" value="Generate" class="btn-default <%=@company.slug%>-bg" >
				</div>
			<% end %>			
		</div>
	</div>
</div>

app/views/divisions/index.html.erb
<div class="container details <%=@company.slug%>">
	<div class="row details-row1">
		<div class="col-xs-12">
	    	<%= render 'index_header' %>    
	    </div>       
	</div> 
	<div class="row form-input" style= "padding: 40px 214px 0;">

			<ul class="list-group"> 
			<%@divisions.order(:order).each do |division| %> 
				<li class="list-group-item" ><%= link_to "#{division.name}", generate_division_path(division) %></li>      
				<%end %>
		</ul>  

		<% unless @company.slug == "coca-cola" %>
			<div class = "row" style= "text-align: center">
				<%= link_to 'Back Home', company_path(id: @company.slug), class: "btn-default #{@company.slug}-border" %>
			</div>
		<% end %>
	</div>
</div>

app/views/divisions/preview_card.html.erb
  
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>

<div class="se-pre-con-<%=@company.slug%>"></div>
<div class="container preview <%=@company.slug%>">
	<div class="row preview-row1">
    	<div class="col-xs-12">
    		<%= render 'preview_card_header' %>   	
      	</div>       
  	</div>
 	<div class="row preview-row2" style="padding-top: 0px"> 
		<div class="col-xs-12 ">
			<div class="generate-form" style="text-align: center;">
				<%= form_tag(division_path(:format=>:pdf), :method => :get) do %>
					<%@card_fields.joins(:divisions).where("division_id = ? ",@division.id).each do |field| %>
						<%= hidden_field_tag "#{field.id}", params[:field_inputs][:"field_#{field.id}"] %>
					<%end%>
	    	    <div class="row preview-row4">
			        <div class="col-xs-12 left">
			        <% if @company.slug == "airschool43" %>				            
									 <input type="submit" style="align: left;" name="250" value= "PRINT" class="btn-default2 <%=@company.slug%>-bg">
			        <% elsif  @company.slug == "coca-cola" %>
									 <input type="text"  pattern="[0-9]{10}" oninvalid="setCustomValidity('Please enter a valid Purchase Order number')" onchange="try{setCustomValidity('')}catch(e){}" name = "Purchase Order" class="form-control print-input" placeholder="Enter your Purchase Order Number here&hellip;" required>

									 <input type="submit" style="align: right;" name="250" value= "PRINT" class="btn-default2 <%=@company.slug%>-bg print-submit">
		            <% else %>
									<input type="submit" style="align: left;" name="250" value= "PRINT" class="btn-default2 <%=@company.slug%>-bg">
								<% end %>

			    	</div>
				</div><br><br>
				<%end%> <!-- END OF FORM TAG -->
			</div>
			<%= render 'card_form_html', division: @division, preview: "true" %>
			<div class="row form-input">
				<br><br><%= link_to 'Back to Input', generate_division_path(@division,back:true), class: "btn-default3 #{@company.slug}-border", style: "margin-left: 0px" %>
				<% if @company.slug != "coca-cola" %>
				<%= link_to 'Back Home', company_path(id: @company.slug), class: "btn-default3 #{@company.slug}-border" %>
				<% end%>
				<br><br><br>
			</div>
		</div>  
		<div class="row preview-row4">
	        <div class="col-xs-12 left">
	            <div>
	            	<div class= "or "></div>
	            </div>
	        </div>       
	    </div>
	</div>  
</div>	

app/views/divisions/preview_email_sig.html.erb
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<!-- <div class="se-pre-con-<%=@company.slug%>"></div> -->
<div class="container preview <%=@company.slug%>">
	<div class="row preview-row1">
    	<div class="col-xs-12">
    		<%= render 'preview_email_sig_header' %>
      	</div>       
  	</div>

</div>

<div style="padding-left:30%">

<div class="js-emaillink">
	<!-- <div class="col-xs-12" style="line-height:1.1">  -->
  <div class="col-xs-9" style="line-height:initial">
	<%= render file: @generated_email_sig_file.path, layout: false, content_type: 'html' %>
	</div>
</div>

</div>

<!-- <div class="container preview "><div class="col-xs-12 row preview-row4"><div class= "or"></div>	</div></div>
 -->
<div class="container preview <%=@company.slug%>">
  <div class="row preview-row4">
    <div class="col-xs-12 left"><div class= "or"></div>

      <ol>
        <li><strong>Copy email signature</strong>. To do so simply click the COPY button below.</li>
        <li>The next step is to paste your email signature into your email client. For detailed instructions on MS Outlook, click the link below:</li>

        <input type="button" value="Instructions for copying email signature to MS Outlook" class="modal-button" data-toggle="modal" data-target="#myModalOutlook" ></button>
      </ol>
  </div></div>
  <div class="row preview-row2" style="padding-top: 0px">
    <div class="col-xs-12">
      <%= link_to 'Back Home', company_path(id: @company.slug), class: "btn-default3 #{@company.slug}-border ", style: "margin-left: 0px" %>
      <%= link_to 'Back to Input', generate_division_path(@division,back:true), class: "btn-default3 #{@company.slug}-border ", style: "margin-left: 0px" %>
      <input type="button" name="commit" value="  COPY  " class="js-emailcopybtn btn-default <%=@company.slug%>-bg" >


     </div>
  </div> 
</div>  






  <!-- Trigger the modal with a button -->
  <!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button> -->

  <!-- Modal -->
  <div class="modal" id="myModalOutlook" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">How to Copy Email Signature to Outlook</h4>
        </div>
        <div class="modal-body">
          <p>With your signature copied open up Outlook. And follow the below steps:<br><br>
                • <strong>Click File – Options</strong>. An Outlook Option pop up will appear</strong><br>
                • <strong>Select Mail</strong> on the left<br>
                • <strong>Click on the Signature option</strong> on the Right<br><br>
                <img src="/assets/modal_images/outlook_instructions1.png"><br><br>
                • With the Signature and Stationary window opened you will need to <strong>select New</strong><br><br>
                Give the Signature a name you will easily be able to identify it with, this is purely for your reference and doesn’t appear in the email.<br><br>
                • Once you have named your email signature all that is left is for you to place it<br><br>
                In the empty edit signature space you will now <strong>paste the signature</strong> you copied in Internet Explorer<br><br>
                <img src="/assets/modal_images/outlook_instructions2.png"><br><br>
                • With the signature now placed click OK and then in the Outlook Options pop up <strong>click OK</strong> again<br><br>
                Your signature should automatically appear when creating a new email and you can set it to automatically be placed on replies/forwards.
              </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  
  <style>
  .modal-button{
     background:none!important;
     border:none; 
     padding:0!important;
     font: inherit;
     /*border is optional*/
     border-bottom:1px solid #444; 
     cursor: pointer;
}
  </style>



<script>
  var copyEmailBtn = document.querySelector('.js-emailcopybtn');  
  copyEmailBtn.addEventListener('click', function(event) {  
      // Select the email link anchor text  
      var emailLink = document.querySelector('.js-emaillink');  
      var range = document.createRange();  
      range.selectNode(emailLink);  
      window.getSelection().addRange(range);  
      try {  
        // Now that we've selected the anchor text, execute the copy command  
        var successful = document.execCommand('copy');  
        var msg = successful ? 'successful' : 'unsuccessful';  
        console.log('Copy email command was ' + msg);  
      } catch(err) {  
        console.log('Oops, unable to copy');  
      }  
      // Remove the selections - NOTE: Should use   
      // removeRange(range) when it is supported  
      window.getSelection().removeAllRanges();  
  });

</script>