config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  match "/" => "pages#home", via: [:gets, :post]


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :companies, :only => [:show]

  resources :divisions, :only => [:index, :new, :create, :show, :destroy, :edit] do

  	member  do 
		  get "generate"
      post "preview"
      get "preview"
      get "completed_job"
  	end  
  end
  get '/robots' => 'pages#robots'
  get '/:id' => 'companies#show'


end

app/models/company.rb
class Company < ApplicationRecord
	has_many :divisions

	extend FriendlyId
	friendly_id :name, use: :slugged

	extend Dragonfly::Model
  	extend Dragonfly::Model::Validations

  	dragonfly_accessor :company_logo


	
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController 

	before_action :set_company, only: [:show]

	def index 
		@companies = Company.all
	end

	def show
     
    if @company.slug == 'coca-cola'
      redirect_to divisions_path(company: @company, function: :business_card)
    end

     reset_session
	end

	def new
		@company = Company.new
	end

	def create
    	@company = Company.new(company_params)

    	respond_to do |format|
    		if @company.save
        		format.html { redirect_to @company, notice: 'Company was successfully created.' }
        		format.json { render :show, status: :created, location: @company }
      		else
        		format.html { render :new }
        		format.json { render json: @company.errors, status: :unprocessable_entity }
      		end
    	end
	end


  private

  def company_params
    params.require(:company).permit(:name, :slug)
  end

  def set_company
    @company = Company.find_by_slug(params[:id])
  end

end

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/index.html.erb
<div class="container">
  <h1>Companies</h1>
  <table>
    <thead>
      <tr>
    <tbody>
      <% @companies.each do |company| %>
        <div class = "row">
        <tr>
          <td><%= company.name %></td>
                    
          <td><%= link_to('Divisions', company_path(company)) %></td>

        </tr>
      <% end %>
      </div>
    </tbody>
  </table>
</div>
  <br>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<br>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="container <%=@company.slug%>">
	<div class="row details-row1">
		<div class="bgimg"><%= image_tag(@company.company_logo.remote_url) %></div>
		<h1>Create It Yourself</h1>
		<h2>Company Stationery and Apparel</h2>
		<%# raise %>
			<div class="row" style= "padding: 40px 214px 0;">
	  			<div class="col-xs-4 form-input">  
	  				<%= link_to image_tag("business_card_button.png"), divisions_path(company: @company, function: :business_card), :style=> "float: right" %>
	  			</div>
				<div class="col-xs-4 form-input">
					<%= link_to image_tag("email_sig_button.png"), divisions_path(company: @company, function: :email_sig) %>
				</div>
				<div class="col-xs-4 form-input">
	  				<!-- <img src="/assets/accesscardspoof.jpg"> -->
	  				<%= link_to image_tag("access_card_button.png"), divisions_path(company: @company, function: :crew_card), :style=> "float: left"  %>
				</div>
				<%#= link_to image_tag(@company.company_logo.remote_url), divisions_path(@company, function: :business_card) %>
			</div>
	</div>
</div>	